apiVersion: apps/v1
kind: Deployment
metadata:
  name: consume-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consume-service
  template:
    metadata:
      labels:
        app: consume-service
    spec:
      containers:
      - name: consume-service
        image: consume-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: consume-service
spec:
  selector:
    app: consume-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
