apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '5002'
    spec:
      containers:
      - name: hello-service
        image: hello-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        env:
        - name: SECRET_KEY
          value: "YOUR_FLASK_SECRET_KEY"
        - name: OIDC_CLIENT_SECRETS
          value: "/app/config/client_secrets.json"
        - name: OIDC_SCOPES
          value: "openid email profile"
        - name: OIDC_INTROSPECTION_AUTH_METHOD
          value: "client_secret_post"
        - name: OVERWRITE_REDIRECT_URI
          value: "http://172.18.0.5/hello/oidc_callback"
        volumeMounts:
        - name: client-secrets
          mountPath: /app/config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: client-secrets
        configMap:
          name: hello-service-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-service-secrets
data:
  client_secrets.json: |
    {
      "web": {
        "client_id": "flask-app",
        "client_secret": "your-client-secret",
        "auth_uri": "http://172.18.0.5/auth/realms/flask-realm/protocol/openid-connect/auth",
        "token_uri": "http://172.18.0.5/auth/realms/flask-realm/protocol/openid-connect/token",
        "issuer": "http://172.18.0.5/auth/realms/flask-realm",
        "userinfo_uri": "http://172.18.0.5/auth/realms/flask-realm/protocol/openid-connect/userinfo",
        "redirect_uris": [
          "http://172.18.0.5/hello/oidc_callback"
        ]
      }
    }
