apiVersion: batch/v1
kind: Job
metadata:
  name: keycloak-config
  namespace: keycloak
spec:
  template:
    spec:
      containers:
      - name: keycloak-config
        image: appropriate/curl
        command: ["/bin/sh", "-c"]
        args:
          - apk add --no-cache jq;
            until curl -sf http://keycloak.keycloak.svc.cluster.local:80/auth/realms/master; do
              echo "Waiting for Keycloak to be ready...";
              sleep 5;
            done;
            sh /scripts/keycloak-config.sh;
        volumeMounts:
        - name: config-volume
          mountPath: /scripts
      restartPolicy: OnFailure
      volumes:
      - name: config-volume
        configMap:
          name: keycloak-config
