apiVersion: apps/v1
kind: Deployment
metadata:
  name: restock-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restock-service
  template:
    metadata:
      labels:
        app: restock-service
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '5002'
    spec:
      containers:
      - name: restock-service
        image: restock-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5002
        livenessProbe:
          httpGet:
            path: /healthz
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5002
          initialDelaySeconds: 30
          periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: restock-service
spec:
  selector:
    app: restock-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5002
